---
title: "exploring MMRF pfs start day"
author: "Dan Rozelle"
date: "March 15, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
source("../curation_scripts.R")
```

```{r}
### joining together all the MMRF variables related to OS and PFS in order to select the most appropriate.
 
p <- GetS3Table(s3.path = file.path(s3, "ClinicalData/OriginalData/MMRF_IA9/PER_PATIENT.csv")) 
# %>%  select(PUBLIC_ID, D_PT_CAUSEOFDEATH, D_PT_pddy, D_PT_pdflag, D_PT_ttfpdw)
v <- GetS3Table(s3.path = file.path(s3, "ClinicalData/OriginalData/MMRF_IA9/PER_PATIENT_VISIT.csv"))
t <- GetS3Table(s3.path = file.path(s3, "ClinicalData/OriginalData/MMRF_IA9/STAND_ALONE_TRTRESP.csv")) %>%
  filter(line == "1" & trtgroup == "1")# & trtstdy > 1)
s <- GetS3Table(s3.path = file.path(s3, "ClinicalData/OriginalData/MMRF_IA9/STAND_ALONE_SURVIVAL.csv")) %>%
  select(public_id, pdflag, censpfs,  ttpfs, ttpfs1,ttpfs2, ttfpd, pfscdy, ttcpfs, ttos, censos, oscdy, ttcos, ttos, deathdy, vis6mo, vis12mo)


ggplot(t, aes(factor(therclass), trtstdy, color = factor(bestrespsh))) +
geom_jitter(alpha = 0.5) + 
  labs(x = "Therapy class",
       y = "first line treatment start day") +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1)
  )


out <- merge(t, p, by.x = "public_id", by.y = "PUBLIC_ID", all = T)

ggplot(out, aes(factor(therclass), trtstdy, color = factor(gsub("(\\d)\\d", "\\1", out$D_PT_age)))) +
geom_jitter(alpha = 0.5) + 
  labs(x = "Therapy class",
       y = "first line treatment start day") +
 
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1)
  )





df <- merge(p,s, by.x = "PUBLIC_ID", by.y = "public_id")
head(df)

### selections for use in integrated dataset
#   df[['D_OS']]       <- unlist(lapply(df$Patient, lookup_by_publicid, dat = survival, field = "ttcos"))
# df[['D_OS_FLAG']]  <- unlist(lapply(df$Patient, lookup_by_publicid, dat = survival, field = "censos"))
# df[['D_PFS']]      <- unlist(lapply(df$Patient, lookup_by_publicid, dat = survival, field = "ttcpfs"))
# df[['D_PFS_FLAG']] <- unlist(lapply(df$Patient, lookup_by_publicid, dat = survival, field = "censpfs"))
# df[['D_PD']]       <- unlist(lapply(df$Patient, lookup_by_publicid, dat = survival, field = "ttfpd"))
# df[['D_PD_FLAG']]  <- unlist(lapply(df$Patient, lookup_by_publicid, dat = survival, field = "pdflag"))
# 

  

```


